# Generated by Django 4.1.5 on 2023-01-21 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('categoria', models.CharField(choices=[('F', 'Familia'), ('A', 'Amigo'), ('S', 'Serviço'), ('R', 'Represetantes')], default='', max_length=1)),
                ('descriçao', models.TextField(blank=True, max_length=300)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
    ]
