# Generated by Django 4.1.5 on 2023-01-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
