# Generated by Django 4.1.5 on 2023-01-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_contatos_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
    ]
