# Generated by Django 4.1.5 on 2023-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_contatos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
